apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: docker-registry
labels:
  - includeSelectors: true
    pairs:
      app: docker-registry
      managedBy: wild-cloud
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
  - namespace.yaml
  - pvc.yaml
