---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-app
  annotations:
    external-dns.alpha.kubernetes.io/target: {{ .cloud.domain }}
    external-dns.alpha.kubernetes.io/cloudflare-proxied: false

    # Optional: Enable HTTPS redirection
    traefik.ingress.kubernetes.io/redirect-entry-point: https

    # Optional: Enable basic auth
    # traefik.ingress.kubernetes.io/auth-type: basic
    # traefik.ingress.kubernetes.io/auth-secret: basic-auth
spec:
  rules:
    - host: example-app.{{ .cloud.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: example-app
                port:
                  number: 80
  tls:
    - hosts:
        - example-app.{{ .cloud.domain }}
      secretName: wildcard-wild-cloud-tls
