---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-wild-cloud
  namespace: cert-manager
spec:
  secretName: wildcard-wild-cloud-tls
  dnsNames:
    - "*.{{ .cloud.domain }}"
    - "{{ .cloud.domain }}"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  privateKey:
    algorithm: RSA
    size: 2048
