---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich-public
  annotations:
    external-dns.alpha.kubernetes.io/target: "{{ .apps.immich.domain }}"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
spec:
  rules:
    - host: "{{ .apps.immich.domain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: immich-server
                port:
                  number: 3001
  tls:
    - secretName: wildcard-wild-cloud-tls
      hosts:
        - "{{ .apps.immich.domain }}"
