---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - image: "{{ .apps.redis.image }}"
          name: redis
          ports:
            - containerPort: {{ .apps.redis.port }}
          env:
            - name: TZ
              value: "{{ .apps.redis.timezone }}"
      restartPolicy: Always
