---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  ports:
    - port: {{ .apps.redis.port }}
      targetPort: {{ .apps.redis.port }}
  selector:
    app: redis
