apiVersion: v1
kind: Service
metadata:
  name: gitea-http
  namespace: gitea
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: {{ .apps.gitea.port }}
  selector:
    component: web
---
apiVersion: v1
kind: Service
metadata:
  name: gitea-ssh
  namespace: gitea
spec:
  type: LoadBalancer
  ports:
  - name: ssh
    port: {{ .apps.gitea.sshPort }}
    targetPort: 2222
    protocol: TCP
  selector:
    component: web